// What a provider actually installs is `plugin/`. It must be a self-contained
// tree: both manifests agree, the marketplaces point at it, and every runtime
// command works from a copy of that directory alone — no repository, no
// `node_modules`, no build step.
import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import { cpSync, existsSync, mkdtempSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative, resolve } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const testDirectory = dirname(fileURLToPath(import.meta.url));
const repositoryRoot = resolve(testDirectory, "../..");
const pluginRoot = resolve(repositoryRoot, "plugin");

function readJson(relativePath) {
  return JSON.parse(readFileSync(resolve(repositoryRoot, relativePath), "utf8"));
}

const codexManifest = readJson("plugin/.codex-plugin/plugin.json");
const claudeManifest = readJson("plugin/.claude-plugin/plugin.json");
const codexMarketplace = readJson(".agents/plugins/marketplace.json");
const claudeMarketplace = readJson(".claude-plugin/marketplace.json");

function pluginFiles(directory = pluginRoot, found = []) {
  for (const entry of readdirSync(directory, { withFileTypes: true }).sort((left, right) => (left.name < right.name ? -1 : 1))) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) pluginFiles(path, found);
    else if (entry.isFile()) found.push(path);
  }
  return found;
}

test("provider manifests identify one versioned ADW plugin and shared skill tree", () => {
  assert.equal(codexManifest.name, "adw");
  assert.equal(claudeManifest.name, "adw");
  assert.equal(codexManifest.version, claudeManifest.version);
  assert.match(codexManifest.version, /^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/);
  assert.equal(codexManifest.skills, "./skills/");
  assert.equal(claudeManifest.skills, "./skills/");
  assert.equal(claudeManifest.workflows, "./workflows/");
  assert.equal(existsSync(join(pluginRoot, "workflows", "execute-phase.mjs")), true);
});

test("repo-local marketplaces point to the approved plugin root", () => {
  const codexEntry = codexMarketplace.plugins.find(({ name }) => name === "adw");
  const claudeEntry = claudeMarketplace.plugins.find(({ name }) => name === "adw");

  assert.ok(codexEntry);
  assert.ok(claudeEntry);
  assert.equal(codexEntry.source.source, "local");
  assert.equal(codexEntry.source.path, "./plugin");
  assert.equal(claudeEntry.source, "./plugin");
  assert.equal(resolve(repositoryRoot, codexEntry.source.path), pluginRoot);
  assert.equal(resolve(repositoryRoot, claudeEntry.source), pluginRoot);
  assert.equal(claudeEntry.version, claudeManifest.version);
  assert.deepEqual(codexEntry.policy, {
    installation: "AVAILABLE",
    authentication: "ON_INSTALL",
  });
  assert.equal(codexEntry.category, "Developer Tools");
});

test("the installed plugin carries no dependencies and exactly one generated file", () => {
  assert.equal(existsSync(join(pluginRoot, "node_modules")), false, "plugin/ must never ship node_modules");
  assert.equal(existsSync(join(pluginRoot, "package.json")), false, "plugin/ must not need an install step");

  const generated = pluginFiles()
    .filter((path) => /\.(?:mjs|js|json|md|sh|txt|rules|toml)$/.test(path) && readFileSync(path, "utf8").includes("@generated"))
    .map((path) => relative(repositoryRoot, path));
  assert.deepEqual(generated, ["plugin/lib/vendor/yaml.mjs"], "every plugin module except the vendored parser is handwritten source");
  assert.match(readFileSync(join(pluginRoot, "lib/vendor/yaml.mjs"), "utf8").split("\n")[0], /^\/\/ @generated by src\/build-vendor\.mjs/);
});

// The headline guarantee of the lean kernel: `plugin/` runs anywhere.
test("every runtime command works from a copy of plugin/ outside the repository", () => {
  const workspace = mkdtempSync(join(tmpdir(), "adw-portable-"));
  const installedPlugin = join(workspace, "installed-plugin");
  cpSync(pluginRoot, installedPlugin, { recursive: true });
  const cli = join(installedPlugin, "bin/adw.mjs");

  // Nothing above the copy can supply a dependency: no ancestor has node_modules.
  for (let directory = installedPlugin; ; directory = dirname(directory)) {
    assert.equal(existsSync(join(directory, "node_modules")), false, `${directory} must not resolve node_modules`);
    if (dirname(directory) === directory) break;
  }
  assert.equal(relative(repositoryRoot, installedPlugin).startsWith(".."), true, "the copy must live outside the repository");

  const project = join(workspace, "project");
  cpSync(resolve(repositoryRoot, "tests/fixtures/existing-project"), project, { recursive: true });
  execFileSync("git", ["init", "-q", "-b", "main"], { cwd: project });
  execFileSync("git", ["config", "user.name", "ADW Test"], { cwd: project });
  execFileSync("git", ["config", "user.email", "adw@example.invalid"], { cwd: project });
  execFileSync("git", ["add", "."], { cwd: project });
  execFileSync("git", ["commit", "-q", "-m", "fixture"], { cwd: project });
  // Run from a neutral working directory so nothing can be picked up from the repository.
  const run = (command, options = [], stdin = "") => {
    const result = spawnSync(process.execPath, [cli, command, ...options], { cwd: workspace, encoding: "utf8", input: stdin });
    let parsed;
    try { parsed = JSON.parse(result.stdout); }
    catch (error) { throw new Error(`${command} did not print JSON (${error.message}): ${result.stdout}${result.stderr}`); }
    assert.equal(result.stderr, "", `${command} must not write to stderr`);
    return { status: result.status, body: parsed };
  };

  // The fixture owns a .devcontainer, so it initializes under provider-sandbox.
  const answers = `${JSON.stringify({ isolation: "provider-sandbox" })}\n`;
  const preview = run("init-preview", ["--project-root", project], answers);
  assert.equal(preview.status, 0, JSON.stringify(preview.body));
  assert.equal(preview.body.ok, true);
  assert.equal(preview.body.writes.some(({ path }) => path === "adw.yaml"), true);

  const applied = run("init-apply", ["--project-root", project, "--fingerprint", preview.body.fingerprint], answers);
  assert.equal(applied.status, 0, JSON.stringify(applied.body));

  const config = run("config", ["--project-root", project]);
  assert.equal(config.status, 0, JSON.stringify(config.body));
  assert.equal(config.body.ok, true);
  assert.equal(config.body.config_source, "adw.yaml");
  assert.equal(config.body.config.adw, 1);
  assert.equal(config.body.validation_commands.length, 0, "validation remains repository evidence until explicitly overridden");

  const doctorReport = run("doctor", ["--project-root", project]);
  assert.equal(doctorReport.body.read_only, true);
  assert.deepEqual(doctorReport.body.checks.filter(({ status }) => status === "fail"), []);
  assert.equal(doctorReport.status, 0, JSON.stringify(doctorReport.body));
});

test("the portable CLI reports an unknown command instead of guessing", () => {
  const workspace = mkdtempSync(join(tmpdir(), "adw-portable-unknown-"));
  const installedPlugin = join(workspace, "installed-plugin");
  cpSync(pluginRoot, installedPlugin, { recursive: true });
  writeFileSync(join(workspace, "marker.txt"), "not a project\n");

  const result = spawnSync(process.execPath, [join(installedPlugin, "bin/adw.mjs"), "explain"], { cwd: workspace, encoding: "utf8" });
  assert.notEqual(result.status, 0);
  const reported = JSON.parse(result.stdout);
  assert.equal(reported.ok, false);
  assert.match(reported.error.message, /unknown command "explain"/);
  for (const command of ["config", "init-preview", "init-apply", "refresh-preview", "refresh-apply", "doctor"]) {
    assert.ok(reported.error.message.includes(command), `${command} must be advertised`);
  }
});

test("Claude strictly validates a copied plugin when the CLI is installed", (t) => {
  const version = spawnSync("claude", ["--version"], { encoding: "utf8" });
  if (version.error?.code === "ENOENT") {
    t.skip("Claude Code is not installed");
    return;
  }
  assert.equal(version.status, 0, version.stderr);

  const workspace = mkdtempSync(join(tmpdir(), "adw-portable-claude-plugin-"));
  const installedPlugin = join(workspace, "installed-plugin");
  cpSync(pluginRoot, installedPlugin, { recursive: true });
  const validation = spawnSync("claude", ["plugin", "validate", "--strict", installedPlugin], { encoding: "utf8" });
  assert.equal(validation.status, 0, `${validation.stdout}${validation.stderr}`);
});
