// `plugin/lib/vendor/yaml.mjs` is the only generated file in the plugin, and
// it exists so the installed plugin can parse YAML without `node_modules`.
// These tests prove the checked-in bytes are current, reproducible, and
// contain nothing but the pinned dependency.
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const builder = join(repositoryRoot, "src/build-vendor.mjs");
const vendorPath = join(repositoryRoot, "plugin/lib/vendor/yaml.mjs");
const nodeModules = join(repositoryRoot, "node_modules");
// The bundler is a development tool; the checked-in artifact is what ships.
const needsInstall = existsSync(join(nodeModules, "esbuild")) ? false : "development dependencies are not installed";

test("the checked-in vendor bundle is current", { skip: needsInstall }, () => {
  const result = spawnSync(process.execPath, [builder, "--check"], { cwd: repositoryRoot, encoding: "utf8" });
  assert.equal(result.status, 0, result.stderr || result.stdout);
  assert.match(result.stdout, /vendor bundle is reproducible and current/);
});

// A standalone copy of everything the bundler reads: its own source, the
// pinned dependency, and a place to write. `esbuild` itself is a build tool and
// is linked rather than copied, so its platform binary stays resolvable.
function scratchBuild(prefix) {
  const scratch = mkdtempSync(join(tmpdir(), prefix));
  mkdirSync(join(scratch, "plugin/lib/vendor"), { recursive: true });
  mkdirSync(join(scratch, "node_modules"), { recursive: true });
  cpSync(join(repositoryRoot, "src"), join(scratch, "src"), { recursive: true });
  cpSync(join(nodeModules, "yaml"), join(scratch, "node_modules/yaml"), { recursive: true });
  symlinkSync(join(nodeModules, "esbuild"), join(scratch, "node_modules/esbuild"), "dir");
  return { scratch, builder: join(scratch, "src/build-vendor.mjs"), output: join(scratch, "plugin/lib/vendor/yaml.mjs") };
}

test("rebuilding in a scratch location reproduces the checked-in bytes", { skip: needsInstall }, () => {
  const { scratch, builder: scratchBuilder, output: rebuiltPath } = scratchBuild("adw-vendor-");
  writeFileSync(rebuiltPath, "placeholder\n");

  const written = spawnSync(process.execPath, [scratchBuilder, "--write"], { cwd: scratch, encoding: "utf8" });
  assert.equal(written.status, 0, written.stderr || written.stdout);
  assert.deepEqual(readFileSync(rebuiltPath), readFileSync(vendorPath), "the bundle must be byte-identical wherever it is built");

  // Building the same inputs twice must not perturb the output either.
  const again = spawnSync(process.execPath, [scratchBuilder, "--write"], { cwd: scratch, encoding: "utf8" });
  assert.equal(again.status, 0, again.stderr || again.stdout);
  assert.deepEqual(readFileSync(rebuiltPath), readFileSync(vendorPath));

  // The repository copy was never touched by the scratch build.
  const check = spawnSync(process.execPath, [builder, "--check"], { cwd: repositoryRoot, encoding: "utf8" });
  assert.equal(check.status, 0, check.stderr || check.stdout);
});

test("a stale vendor bundle is reported instead of silently accepted", { skip: needsInstall }, () => {
  const { scratch, builder: scratchBuilder, output } = scratchBuild("adw-vendor-stale-");
  writeFileSync(output, `${readFileSync(vendorPath, "utf8")}\n// drift\n`);

  const result = spawnSync(process.execPath, [scratchBuilder, "--check"], { cwd: scratch, encoding: "utf8" });
  assert.equal(result.status, 1);
  assert.match(result.stderr, /plugin\/lib\/vendor\/yaml\.mjs is stale; run npm run build:vendor/);
});

test("the vendor module exports a working parseDocument", async () => {
  const { parseDocument } = await import(vendorPath);
  assert.equal(typeof parseDocument, "function");

  const document = parseDocument("adw: 1\ngit:\n  base_branch: \"main\"\n", { merge: false, strict: true, uniqueKeys: true, version: "1.2" });
  assert.deepEqual(document.errors, []);
  assert.deepEqual(document.toJS(), { adw: 1, git: { base_branch: "main" } });

  const broken = parseDocument("adw: 1\n  : broken\n:\n", { strict: true, uniqueKeys: true, version: "1.2" });
  assert.ok(broken.errors.length > 0, "parse errors must be reported rather than swallowed");
});

test("nothing handwritten is bundled into the vendor module", () => {
  const bundle = readFileSync(vendorPath, "utf8");

  assert.match(bundle.split("\n")[0], /^\/\/ @generated by src\/build-vendor\.mjs from the pinned `yaml` dependency\. Do not edit\.$/);
  for (const identifier of [
    "validateProjectConfig",
    "applyAtomicWrites",
    "CODEX_RULES",
    "managedDevelopmentFiles",
    "discoverDevelopmentEnvironment",
    "runDoctor",
    "planInitialization",
    "PERMISSION_PROFILE",
    "adw.yaml",
    "ADW_MANAGED_DEVCONTAINER",
  ]) {
    assert.equal(bundle.includes(identifier), false, `${identifier} must not be bundled into the vendored parser`);
  }
  // Only the vendored parser is exported; the plugin's own modules stay as source.
  assert.deepEqual([...bundle.matchAll(/^export \{[\s\S]*?\};$/gm)].length, 1);
  assert.match(bundle, /parseDocument/);
});
