// Codex and Claude permission policy generation.
//
// Both providers run the same skills, so both receive the same semantic
// authorization categories: ordinary local development is automatic, external
// or destructive effects either prompt or are refused outright. Only the
// syntax differs. `docs/security.md` documents the categories; the contract
// tests prove the two renderings stay in step.
import { ContractError } from "./safe-files.mjs";
import { defaultPermissionPolicy, effectiveEntries } from "./permission-policy.mjs";

export const PERMISSION_PROFILE = "managed-development";

const BASE_CODEX_RULES = `# Generated by ADW. Most restrictive matching rule wins.
# Routine workspace development and local Git history are automatic.

prefix_rule(pattern = ["git", ["status", "diff", "log", "show", "blame", "grep", "ls-files", "rev-parse"]], decision = "allow")
prefix_rule(pattern = ["git", "config", ["--get", "--get-all", "--list"]], decision = "allow")
prefix_rule(pattern = ["git", "remote", ["-v", "get-url"]], decision = "allow")
prefix_rule(pattern = ["git", "worktree", "list"], decision = "allow")
prefix_rule(pattern = ["git", "worktree", "add"], decision = "allow")
prefix_rule(pattern = ["git", ["add", "commit"]], decision = "allow")
prefix_rule(pattern = ["git", "switch", ["-c", "--create"]], decision = "allow")

prefix_rule(pattern = [["npm", "pnpm", "yarn", "bun"], ["test", "install", "ci"]], decision = "allow")
prefix_rule(pattern = [["npm", "pnpm", "yarn", "bun"], "run", ["build", "check", "lint", "test", "typecheck"]], decision = "allow")
prefix_rule(pattern = ["dotnet", ["build", "format", "restore", "test"]], decision = "allow")
prefix_rule(pattern = ["cargo", ["build", "check", "clippy", "fetch", "fmt", "test"]], decision = "allow")
prefix_rule(pattern = ["go", ["build", "fmt", "test", "vet"]], decision = "allow")
prefix_rule(pattern = ["go", "mod", "download"], decision = "allow")
prefix_rule(pattern = [["pytest", "ruff", "mypy"]], decision = "allow")
prefix_rule(pattern = ["python", "-m", ["pytest", "ruff", "mypy"]], decision = "allow")
prefix_rule(pattern = ["make", ["build", "check", "lint", "test"]], decision = "allow")

# Pushing, branch deletion, worktree removal, rebase, merge, and discarding
# tracked changes always reach a person. In managed devcontainers the
# root-owned git wrapper additionally rejects force and delete pushes before
# delegating to Git.
prefix_rule(pattern = ["git", "push"], decision = "prompt")
prefix_rule(pattern = ["git", "tag"], decision = "prompt")
prefix_rule(pattern = ["git", "branch", ["-d", "-D", "--delete"]], decision = "prompt")
prefix_rule(pattern = ["git", "worktree", ["remove", "prune"]], decision = "prompt")
prefix_rule(pattern = ["git", ["rebase", "merge", "restore", "checkout"]], decision = "prompt")
prefix_rule(pattern = ["git", "reset"], decision = "prompt")
prefix_rule(pattern = ["az", "boards", "query"], decision = "allow")
prefix_rule(pattern = ["az", "boards", "work-item", "show"], decision = "allow")
prefix_rule(pattern = ["az", "repos", "pr", ["list", "show"]], decision = "allow")
prefix_rule(pattern = ["az", "boards", "work-item", ["create", "delete", "update"]], decision = "prompt")
prefix_rule(pattern = ["az", "repos", "pr", ["create", "update"]], decision = "prompt")
prefix_rule(pattern = ["az", "devops", "invoke"], decision = "prompt")
prefix_rule(pattern = [["glab", "jira"]], decision = "prompt")

prefix_rule(pattern = ["git", "push", ["--force", "--force-with-lease", "-f", "--mirror"]], decision = "forbidden")
prefix_rule(pattern = ["git", "reset", "--hard"], decision = "forbidden")
prefix_rule(pattern = ["git", "clean", ["-f", "-fd", "-fdx", "-fx"]], decision = "forbidden")
prefix_rule(pattern = [["npm", "pnpm", "yarn"], ["publish", "unpublish"]], decision = "forbidden")
prefix_rule(pattern = ["dotnet", "nuget", ["delete", "push"]], decision = "forbidden")
prefix_rule(pattern = [["kubectl", "helm", "terraform"], ["apply", "delete", "destroy", "install", "uninstall", "upgrade"]], decision = "forbidden")
prefix_rule(pattern = ["gh", "auth", "token"], decision = "forbidden")
`;

const CODEX_DECISION = Object.freeze({ allow: "allow", ask: "prompt", deny: "forbidden" });

export function renderCodexRules(policy = defaultPermissionPolicy()) {
  const rules = effectiveEntries(policy)
    .filter(({ kind }) => kind === "command")
    .map(({ pattern, decision }) => `prefix_rule(pattern = ${JSON.stringify(pattern)}, decision = "${CODEX_DECISION[decision]}")`);
  return `${BASE_CODEX_RULES.trimEnd()}\n\n# Project provider-operation policy.\n${rules.join("\n")}\n`;
}

export const CODEX_RULES = renderCodexRules();

const CODEX_START = "# ADW:MANAGED-DEVELOPMENT:START";
const CODEX_END = "# ADW:MANAGED-DEVELOPMENT:END";
const CODEX_APPS_START = "# ADW:PROVIDER-PERMISSIONS:START";
const CODEX_APPS_END = "# ADW:PROVIDER-PERMISSIONS:END";
const CODEX_ROOT_SETTINGS = [
  'approval_policy = "on-request"',
  'sandbox_mode = "workspace-write"',
  'web_search = "live"',
];

function topLevelTomlValue(source, key) {
  let inTable = false;
  for (const line of source.split(/\r?\n/)) {
    if (/^\s*\[/.test(line)) inTable = true;
    if (inTable) continue;
    const match = new RegExp(`^\\s*${key}\\s*=\\s*(["'])([^"']+)\\1\\s*(?:#.*)?$`).exec(line);
    if (match) return match[2];
  }
  return undefined;
}

function tableTomlValue(source, table, key) {
  const escaped = table.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const section = new RegExp(`^\\s*\\[${escaped}\\]\\s*$([\\s\\S]*?)(?=^\\s*\\[|(?![\\s\\S]))`, "m").exec(source)?.[1];
  if (!section) return undefined;
  return new RegExp(`^\\s*${key}\\s*=\\s*(["'])([^"']+)\\1\\s*(?:#.*)?$`, "m").exec(section)?.[2];
}

function ensureCodexAppApproval(source) {
  const section = /^\[apps\._default\]\s*$([\s\S]*?)(?=^\[|(?![\s\S]))/m.exec(source);
  if (!section) {
    const separator = source.length === 0 || source.endsWith("\n") ? "" : "\n";
    return `${source}${separator}\n[apps._default]\ndefault_tools_approval_mode = "writes"\n`;
  }
  const value = /^\s*default_tools_approval_mode\s*=\s*(["'])([^"']+)\1/m.exec(section[1])?.[2];
  if (value && value !== "writes") throw new ContractError(`.codex/config.toml apps._default.default_tools_approval_mode conflicts with ${PERMISSION_PROFILE}`);
  if (value) return source;
  const insertion = `${section[0].split("\n")[0]}\ndefault_tools_approval_mode = "writes"${section[1]}`;
  return source.slice(0, section.index) + insertion + source.slice(section.index + section[0].length);
}

function replaceCodexProviderBlock(source, policy) {
  const start = source.indexOf(CODEX_APPS_START);
  const end = source.indexOf(CODEX_APPS_END);
  if ((start === -1) !== (end === -1) || start > end) throw new ContractError(".codex/config.toml has an invalid ADW provider-permissions block");
  if (start !== -1) source = `${source.slice(0, start)}${source.slice(end + CODEX_APPS_END.length)}`.replace(/\n{3,}/g, "\n\n");
  const lines = [CODEX_APPS_START];
  const mode = { allow: "approve", ask: "prompt" };
  for (const entry of effectiveEntries(policy).filter(({ kind }) => kind === "tool")) {
    const app = JSON.stringify(entry.app);
    const tool = JSON.stringify(entry.tool);
    lines.push(``, `[apps.${app}.tools.${tool}]`);
    if (entry.decision === "deny") lines.push("enabled = false");
    else lines.push(`approval_mode = "${mode[entry.decision]}"`);
  }
  lines.push("", CODEX_APPS_END);
  return `${source.trimEnd()}\n\n${lines.join("\n")}\n`;
}

export function mergeCodexConfig(source = "", policy = defaultPermissionPolicy()) {
  if (source.includes(CODEX_START) || source.includes(CODEX_END)) {
    const starts = source.split(CODEX_START).length - 1;
    const ends = source.split(CODEX_END).length - 1;
    if (starts !== 1 || ends !== 1 || source.indexOf(CODEX_START) > source.indexOf(CODEX_END)) throw new ContractError(".codex/config.toml has an invalid ADW managed block");
  }
  for (const [key, expected] of [["approval_policy", "on-request"], ["sandbox_mode", "workspace-write"], ["web_search", "live"]]) {
    const value = topLevelTomlValue(source, key);
    if (value && value !== expected) throw new ContractError(`.codex/config.toml ${key}=${JSON.stringify(value)} conflicts with ${PERMISSION_PROFILE}`);
  }
  const activeProfile = topLevelTomlValue(source, "profile");
  if (activeProfile) {
    for (const [key, expected] of [["approval_policy", "on-request"], ["sandbox_mode", "workspace-write"], ["web_search", "live"]]) {
      const value = tableTomlValue(source, `profiles.${activeProfile}`, key);
      if (value && value !== expected) throw new ContractError(`.codex/config.toml active profile ${JSON.stringify(activeProfile)} sets ${key}=${JSON.stringify(value)}, which conflicts with ${PERMISSION_PROFILE}`);
    }
  }
  const missing = CODEX_ROOT_SETTINGS.filter((line) => !topLevelTomlValue(source, line.split(" = ")[0]));
  if (missing.length > 0 && source.includes(CODEX_START)) {
    const end = source.indexOf(CODEX_END);
    const separator = source.slice(0, end).endsWith("\n") ? "" : "\n";
    source = `${source.slice(0, end)}${separator}${missing.join("\n")}\n${source.slice(end)}`;
  } else if (missing.length > 0) {
    source = `${CODEX_START}\n${missing.join("\n")}\n${CODEX_END}\n${source.replace(/^\n+/, "")}`;
  }
  return replaceCodexProviderBlock(ensureCodexAppApproval(source).replace(/^\n+/, ""), policy);
}

export const CLAUDE_ASK = [
  "Bash(git push *)", "Bash(git tag *)", "Bash(git rebase *)", "Bash(git merge *)", "Bash(git reset *)",
  "Bash(git worktree remove *)", "Bash(git worktree prune *)",
  "Bash(gh api *)",
  "Bash(gh pr close *)", "Bash(gh pr comment *)", "Bash(gh pr create *)", "Bash(gh pr edit *)", "Bash(gh pr ready *)", "Bash(gh pr reopen *)", "Bash(gh pr review *)",
  "Bash(gh issue close *)", "Bash(gh issue comment *)", "Bash(gh issue create *)", "Bash(gh issue delete *)", "Bash(gh issue edit *)", "Bash(gh issue reopen *)",
  "Bash(gh run cancel *)", "Bash(gh run delete *)", "Bash(gh run rerun *)", "Bash(gh workflow disable *)", "Bash(gh workflow enable *)", "Bash(gh workflow run *)",
  "Bash(az boards work-item create *)", "Bash(az boards work-item delete *)", "Bash(az boards work-item update *)", "Bash(az repos pr create *)", "Bash(az repos pr update *)", "Bash(az devops invoke *)",
  "Bash(git branch -d *)", "Bash(git branch -D *)", "Bash(git checkout -- *)", "Bash(git restore --worktree *)", "Bash(rm -rf *)",
  "Bash(npm run release *)", "Bash(npm run publish *)", "Bash(npm run deploy *)", "Bash(pnpm run release *)", "Bash(pnpm run publish *)", "Bash(pnpm run deploy *)",
  "Bash(yarn run release *)", "Bash(yarn run publish *)", "Bash(yarn run deploy *)", "Bash(bun run release *)", "Bash(bun run publish *)", "Bash(bun run deploy *)",
  "Bash(docker push *)", "Bash(ssh *)", "Bash(scp *)", "Bash(sftp *)",
  "Bash(curl * -X POST *)", "Bash(curl * -X PUT *)", "Bash(curl * -X PATCH *)", "Bash(curl * -X DELETE *)",
  "Bash(curl * --data *)", "Bash(curl * --upload-file *)", "Bash(wget * --post-data *)", "Bash(wget * --post-file *)",
  // `acceptEdits` auto-accepts ordinary file edits, so the policy files that carry
  // this profile would otherwise be rewritable without review. Ask instead of deny:
  // a maintainer still edits them deliberately, and `adw:doctor` repairs them
  // through its reviewed preview rather than the Edit tool. Claude Code's file
  // permission rules only match `Edit(path)` — a `Write(path)` rule is never
  // matched, so listing both is dead weight (and current Claude Code warns
  // about it at startup).
  "Edit(./.claude/settings.json)",
  "Edit(./.codex/config.toml)",
  "Edit(./.codex/rules/adw.rules)",
  "Edit(./adw.yaml)",
  "Edit(./.devcontainer/**)",
];

export const CLAUDE_DENY = [
  "Bash(git push --force *)", "Bash(git push --force-with-lease *)", "Bash(git push -f *)",
  "Bash(git push --mirror *)", "Bash(git push * --force *)", "Bash(git push * --force-with-lease *)", "Bash(git push * -f *)", "Bash(git push * +*)",
  "Bash(git reset --hard *)", "Bash(git clean -f *)", "Bash(git clean -fd *)", "Bash(git clean -fdx *)",
  "Bash(gh pr merge *)", "Bash(gh release create *)", "Bash(gh release delete *)", "Bash(gh release edit *)", "Bash(gh release upload *)",
  "Bash(npm publish *)", "Bash(npm unpublish *)", "Bash(pnpm publish *)", "Bash(yarn publish *)", "Bash(dotnet nuget push *)", "Bash(dotnet nuget delete *)",
  "Bash(kubectl apply *)", "Bash(kubectl delete *)", "Bash(helm install *)", "Bash(helm upgrade *)", "Bash(helm uninstall *)", "Bash(terraform apply *)", "Bash(terraform destroy *)",
  // Both spellings: a bare `gh auth token` has no trailing argument to glob.
  "Bash(gh auth token)", "Bash(gh auth token *)",
  "Read(./.env)", "Read(./.env.*)", "Read(~/.ssh/**)",
];

export const CLAUDE_ALLOW = ["WebSearch"];

function union(...groups) {
  return [...new Set(groups.flatMap((group) => (Array.isArray(group) ? group : [])))];
}

function claudeToolRules(policy) {
  const result = { allow: [], ask: [], deny: [] };
  for (const entry of effectiveEntries(policy).filter(({ kind }) => kind === "tool")) {
    result[entry.decision].push(`mcp__${entry.mcp_server}__${entry.tool}`);
  }
  return result;
}

export function mergeClaudeSettings(source = "", policy = defaultPermissionPolicy()) {
  let settings = {};
  if (source.trim()) {
    try { settings = JSON.parse(source); }
    catch (error) { throw new ContractError(`cannot merge .claude/settings.json: ${error.message}`); }
  }
  if (!settings || typeof settings !== "object" || Array.isArray(settings)) throw new ContractError(".claude/settings.json must contain one JSON object");
  const permissions = settings.permissions && typeof settings.permissions === "object" && !Array.isArray(settings.permissions) ? { ...settings.permissions } : {};
  if (permissions.defaultMode && permissions.defaultMode !== "acceptEdits") throw new ContractError(`.claude/settings.json permissions.defaultMode=${JSON.stringify(permissions.defaultMode)} conflicts with ${PERMISSION_PROFILE}`);
  if (permissions.allow !== undefined && !Array.isArray(permissions.allow)) throw new ContractError(".claude/settings.json permissions.allow must be an array");
  if ((permissions.allow ?? []).some((rule) => typeof rule !== "string")) throw new ContractError(".claude/settings.json permissions.allow entries must be strings");
  if ((permissions.allow ?? []).some((rule) => /^mcp__\*$/.test(rule))) throw new ContractError(".claude/settings.json contains a broad MCP allow rule that conflicts with managed external-write review");
  const bashAllows = (permissions.allow ?? []).filter((rule) => typeof rule === "string" && /^Bash(?:\(|$)/.test(rule));
  if (bashAllows.length > 0) throw new ContractError(`.claude/settings.json contains Bash allow rules that ${PERMISSION_PROFILE} cannot preserve safely; review and remove them explicitly: ${bashAllows.join(", ")}`);
  permissions.defaultMode = "acceptEdits";
  permissions.disableBypassPermissionsMode = "disable";
  const existingAllows = (permissions.allow ?? []).filter((rule) => typeof rule === "string");
  const toolRules = claudeToolRules(policy);
  permissions.allow = union(existingAllows, CLAUDE_ALLOW, toolRules.allow);
  permissions.ask = union(permissions.ask, CLAUDE_ASK, toolRules.ask);
  permissions.deny = union(permissions.deny, CLAUDE_DENY, toolRules.deny);
  const sandbox = settings.sandbox && typeof settings.sandbox === "object" && !Array.isArray(settings.sandbox) ? { ...settings.sandbox } : {};
  for (const key of ["enabled", "failIfUnavailable", "autoAllowBashIfSandboxed"]) if (sandbox[key] === false) throw new ContractError(`.claude/settings.json sandbox.${key}=false conflicts with ${PERMISSION_PROFILE}`);
  if (sandbox.allowUnsandboxedCommands === true) throw new ContractError(`.claude/settings.json sandbox.allowUnsandboxedCommands=true conflicts with ${PERMISSION_PROFILE}`);
  if (sandbox.filesystem?.disabled === true || sandbox.enableWeakerNestedSandbox === true || (Array.isArray(sandbox.excludedCommands) && sandbox.excludedCommands.length > 0)) throw new ContractError(`.claude/settings.json weakens the ${PERMISSION_PROFILE} sandbox`);
  Object.assign(sandbox, { enabled: true, failIfUnavailable: true, autoAllowBashIfSandboxed: true, allowUnsandboxedCommands: false });
  return `${JSON.stringify({ $schema: settings.$schema ?? "https://json.schemastore.org/claude-code-settings.json", ...settings, permissions, sandbox }, null, 2)}\n`;
}

// The container-owned Claude policy: the project settings above plus the
// egress allowlist and the root-installed effect-classification hook.
export function managedClaudeSettings({ allowedDomains = [], webAccess = "public-pages", policy = defaultPermissionPolicy() } = {}) {
  if (!["hosted-only", "public-pages"].includes(webAccess)) throw new ContractError(`unsupported web access profile: ${webAccess}`);
  const settings = JSON.parse(mergeClaudeSettings("", policy));
  // Bubblewrap cannot create the Linux user namespace its nested sandbox
  // needs here: the managed image deliberately never grants CAP_SYS_ADMIN or
  // apparmor=unconfined (see execution:hardening), so unshare(CLONE_NEWUSER)
  // is rejected outright and every bwrap invocation fails before it can do
  // anything, sandboxed or not. failIfUnavailable/allowUnsandboxedCommands do
  // not paper over that: they cover a missing sandbox dependency and a
  // command the sandbox denies, not the sandbox failing to launch, and
  // Claude Code's own auto-mode classifier treats the resulting
  // dangerouslyDisableSandbox retry as an escalation that needs approval no
  // hook here can grant (this profile deliberately disables
  // bypassPermissions) -- so left at the default, every single Bash call
  // dead-ends. There is no bwrap workaround for a container hardened this
  // way (verified directly: even a bare `bwrap --unshare-user` fails the
  // same way, so enableWeakerNestedSandbox's /proc bind-mount trick, which
  // addresses a later step, never gets reached either). The nested sandbox
  // is turned off entirely instead; the outer container -- non-root, dropped
  // capabilities, fail-closed egress, this same ask/deny policy enforced by
  // the PreToolUse hook below -- is the isolation boundary here. Outside this
  // container (a bare host with no other boundary), mergeClaudeSettings still
  // fails closed by default.
  settings.sandbox.enabled = false;
  settings.sandbox.network = {
    allowedDomains: [...new Set(allowedDomains)].sort(),
    strictAllowlist: true,
    ...(webAccess === "hosted-only" ? { allowManagedDomainsOnly: true } : {}),
  };
  settings.hooks = {
    PreToolUse: [
      { matcher: "Bash", hooks: [{ type: "command", command: "/usr/local/bin/adw-claude-permission-hook" }] },
      { matcher: "^mcp__.*$", hooks: [{ type: "command", command: "/usr/local/bin/adw-claude-permission-hook" }] },
    ],
  };
  return `${JSON.stringify(settings, null, 2)}\n`;
}

export const PERMISSION_FILES = Object.freeze([".codex/config.toml", ".codex/rules/adw.rules", ".claude/settings.json"]);

// Both providers share one skill tree, so every project gets both policies.
export function permissionProjectFiles(readExisting = () => "", { repairManagedRules = false, policy = defaultPermissionPolicy() } = {}) {
  const rules = renderCodexRules(policy);
  const existingRules = readExisting(".codex/rules/adw.rules");
  if (!repairManagedRules && existingRules && existingRules !== rules) throw new ContractError(".codex/rules/adw.rules differs from the ADW managed-development policy");
  return [
    { path: ".codex/config.toml", content: mergeCodexConfig(readExisting(".codex/config.toml"), policy) },
    { path: ".codex/rules/adw.rules", content: rules },
    { path: ".claude/settings.json", content: mergeClaudeSettings(readExisting(".claude/settings.json"), policy) },
  ];
}
