#!/usr/bin/env node
// Bundles the pinned `yaml` dependency into plugin/lib/vendor/yaml.mjs so the
// installed plugin runs without repository `node_modules`. Nothing handwritten
// is bundled: every first-party module ships as its own source file.
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const sourceDirectory = dirname(fileURLToPath(import.meta.url));
const repositoryRoot = resolve(sourceDirectory, "..");
const sourcePath = resolve(sourceDirectory, "vendor/yaml-entry.mjs");
const outputPath = resolve(repositoryRoot, "plugin/lib/vendor/yaml.mjs");

const options = {
  entryPoints: [sourcePath],
  outfile: outputPath,
  bundle: true,
  format: "esm",
  platform: "node",
  target: "node20",
  legalComments: "none",
  sourcemap: false,
  logLevel: "silent",
  // `yaml` reaches for `process` through CommonJS interop, so the bundle needs a
  // real `require` even though it ships as ESM.
  banner: { js: '// @generated by src/build-vendor.mjs from the pinned `yaml` dependency. Do not edit.\nimport { createRequire as __adwCreateRequire } from "node:module"; const require = __adwCreateRequire(import.meta.url);' },
};

if (process.argv.includes("--write")) {
  await build({ ...options, write: true });
  process.stdout.write(`wrote ${outputPath}\n`);
} else {
  const generated = await build({ ...options, write: false });
  const output = await readFile(outputPath);
  const bundled = generated.outputFiles.find(({ path }) => resolve(path) === outputPath)?.contents ?? generated.outputFiles[0]?.contents;
  if (!bundled || !Buffer.from(bundled).equals(output)) {
    process.stderr.write("plugin/lib/vendor/yaml.mjs is stale; run npm run build:vendor\n");
    process.exitCode = 1;
  } else {
    process.stdout.write("vendor bundle is reproducible and current\n");
  }
}
